[phases.setup]
nixPkgs = ['php82', 'php82Extensions.intl', 'php82Extensions.zip', 'php82Extensions.gd', 'php82Extensions.pdo_mysql']

[phases.install]
cmds = [
    'composer install --optimize-autoloader --no-dev --no-interaction',
    'npm install',
    'npm run build'
]

[phases.build]
cmds = [
    'php artisan config:cache',
    'php artisan route:cache',
    'php artisan view:cache'
]

[start]
cmd = 'php artisan migrate --force && php artisan storage:link && php artisan serve --host=0.0.0.0 --port=${PORT:-8000}'
